EXTRA_CFLAGS += -Ilge/include
obj-$(CONFIG_LGE_BACKLIGHT_LM3530) += backlight_lm3530.o
obj-$(CONFIG_LGE_BACKLIGHT_LM3537) += backlight_lm3537.o
obj-$(CONFIG_LGE_DISPLAY_MIPI_LGIT_IJB_VIDEO_HD_PT) += lcd_mipi_lgit.o lcd_mipi_lgit_video_hd_pt.o
obj-$(CONFIG_LGE_DISPLAY_MIPI_LGD_VIDEO_WVGA_PT) += lcd_mipi_lgd.o lcd_mipi_lgd_video_wvga_pt.o
